### ISSUE TITLE
Lists of Dicts Template Generation

### ISSUE THREAD

**Issue by jammont** [jammont/mlky#1]
Template generation using a definitions file with a section that is a list of dicts isn't well supported. Ideally something along the lines of the following:

`definitions.yml`
```yaml
sect:
 .type: list
 .template: 2
 .children:
  param1:
   .type: int
   .defaults: [11, 21]
  param2:
   .type: int
   .defaults: [12, 22]
```

`template.yml`
```yaml
sect:
 - name: s1
   param1: 11
   param2: 12
 - name: 2
   param1: 11
   param2: 12
```

The `.template` would be an integer for the number of subsections to generate. Each subsection would attempt to set the defaults for its parameters to be the index of the `.defaults` keyword. In pseudo code:

```python
for i in range(defs[sect].template):
  sect[i] = {
    param1 = param1.defaults[i] or param1.default
    param2 = param2.defaults[i] or param2.default
  }
```
