### ISSUE TITLE
CLI Override Support

### ISSUE THREAD

**Issue by jammont** [jammont/mlky#17]
Create a syntax that allows easy passing a command line option to override keys in a config.

Example:
```
python script -c config.yml --override target: abc, data: test: xyz, train: mno,, plots: false
```
Would translate to:
```yaml
target: abc
data:
  test: xyz
  train: mno
plots: false
```
