### ISSUE TITLE
Patch within config

### ISSUE THREAD

**Issue by jammont** [jammont/mlky#18]
Add the ability to set patching within the config file. Something like

```
A:
  ...
B:
  $patch: A
C:
  $patch: B
D:
  $patch: B
E:
  ...
F:
  $patch: A<-E
```
The above would auto convert to:
```
A
A<-B
A<-B<-C
A<-B<-D
E
A<-E<-F
```
